### ISSUE TITLE
Aspen crashes with DistributionNotFound: Cheroot==4.0.0beta

### ISSUE THREAD

**Issue by amitkot** [gratipay/aspen-python#408]
Hi,
My website uses aspen and gunicorn and runs from Heroku.

When I start it, it runs fine, but occasionally it just crashes. Manually restarting gets it running again.

Looking at the logs on Heroku, I see the following:

```
2015-01-11T15:27:28.250536+00:00 app[web.1]: [2015-01-11 15:27:28 +0000] [13] [ERROR] Exception in worker process:
2015-01-11T15:27:28.250541+00:00 app[web.1]: Traceback (most recent call last):
2015-01-11T15:27:28.250548+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2015-01-11T15:27:28.250549+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 66, in wsgi
2015-01-11T15:27:28.250554+00:00 app[web.1]:     return self.load_wsgiapp()
2015-01-11T15:27:28.250557+00:00 app[web.1]:     return util.import_app(self.app_uri)
2015-01-11T15:27:28.250559+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 356, in import_app
2015-01-11T15:27:28.250560+00:00 app[web.1]:     __import__(module)
2015-01-11T15:27:28.250562+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/aspen/wsgi.py", line 20, in <module>
2015-01-11T15:27:28.250545+00:00 app[web.1]:     worker.init_process()
2015-01-11T15:27:28.250543+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
2015-01-11T15:27:28.250551+00:00 app[web.1]:     self.callable = self.load()
2015-01-11T15:27:28.250556+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2015-01-11T15:27:28.250566+00:00 app[web.1]:     self.configure(argv)
2015-01-11T15:27:28.250569+00:00 app[web.1]:     render_module = entrypoint.load()
2015-01-11T15:27:28.250546+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 114, in init_process
2015-01-11T15:27:28.250553+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2015-01-11T15:27:28.250565+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/aspen/website.py", line 35, in __init__
2015-01-11T15:27:28.250568+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/aspen/configuration/__init__.py", line 278, in configure
2015-01-11T15:27:28.250563+00:00 app[web.1]:     website = Website([])
2015-01-11T15:27:28.250575+00:00 app[web.1]:     items = working_set.resolve(reqs, env, installer)
2015-01-11T15:27:28.250577+00:00 app[web.1]:   File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 639, in resolve
2015-01-11T15:27:28.250578+00:00 app[web.1]:     raise DistributionNotFound(req)
2015-01-11T15:27:28.250572+00:00 app[web.1]:     if require: self.require(env, installer)
2015-01-11T15:27:28.250570+00:00 app[web.1]:   File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2145, in load
2015-01-11T15:27:28.250574+00:00 app[web.1]:   File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2159, in require
2015-01-11T15:27:28.250582+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
2015-01-11T15:27:28.250589+00:00 app[web.1]:     self.callable = self.load()
2015-01-11T15:27:28.250587+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2015-01-11T15:27:28.250584+00:00 app[web.1]:     worker.init_process()
2015-01-11T15:27:28.250580+00:00 app[web.1]: DistributionNotFound: Cheroot==4.0.0beta
2015-01-11T15:27:28.250581+00:00 app[web.1]: Traceback (most recent call last):
2015-01-11T15:27:28.250585+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 114, in init_process
2015-01-11T15:27:28.250588+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 66, in wsgi
2015-01-11T15:27:28.250592+00:00 app[web.1]:     return self.load_wsgiapp()
2015-01-11T15:27:28.250594+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2015-01-11T15:27:28.250591+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2015-01-11T15:27:28.250595+00:00 app[web.1]:     return util.import_app(self.app_uri)
2015-01-11T15:27:28.250598+00:00 app[web.1]:     __import__(module)
2015-01-11T15:27:28.250600+00:00 app[web.1]:     website = Website([])
2015-01-11T15:27:28.250596+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 356, in import_app
2015-01-11T15:27:28.250602+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/aspen/website.py", line 35, in __init__
2015-01-11T15:27:28.250604+00:00 app[web.1]:     self.configure(argv)
2015-01-11T15:27:28.250605+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/aspen/configuration/__init__.py", line 278, in configure
2015-01-11T15:27:28.250606+00:00 app[web.1]:     render_module = entrypoint.load()
2015-01-11T15:27:28.250608+00:00 app[web.1]:   File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2145, in load
2015-01-11T15:27:28.250609+00:00 app[web.1]:     if require: self.require(env, installer)
2015-01-11T15:27:28.250610+00:00 app[web.1]:   File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2159, in require
2015-01-11T15:27:28.250599+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/aspen/wsgi.py", line 20, in <module>
2015-01-11T15:27:28.250612+00:00 app[web.1]:     items = working_set.resolve(reqs, env, installer)
2015-01-11T15:27:28.250679+00:00 app[web.1]:   File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 639, in resolve
2015-01-11T15:27:28.250682+00:00 app[web.1]:     raise DistributionNotFound(req)
2015-01-11T15:27:28.250684+00:00 app[web.1]: DistributionNotFound: Cheroot==4.0.0beta
```

I do not have Cheroot installed as a dependency, this is my requirements.txt file:
```
./vendor/Jinja2-2.7.3.tar.gz
./vendor/Markdown-2.5.2.tar.gz
./vendor/MarkupSafe-0.23.tar.gz
./vendor/aspen-0.35-py2-none-any.whl
./vendor/aspen-jinja2-0.4.tar.bz2
./vendor/honcho-0.5.0.tar.gz
./vendor/ipython-2.3.1-py27-none-any.whl
./vendor/ipdb-0.8.zip
./vendor/livereload-2.3.2.tar.gz
./vendor/mimeparse-0.1.3.tar.gz
./vendor/tornado-4.0.2.tar.gz
./vendor/wsgiref-0.1.2.zip
./vendor/Pygments-2.0.1-py2-none-any.whl
./vendor/gunicorn-19.1.1-py2.py3-none-any.whl
```

Any idea?

**Comment by whit537** [comment]
We used to depend on Cheroot but haven't since [0.31](https://github.com/gratipay/aspen-python/blob/master/Changelog.md#031---released-tue-may--6-2014-by-pjz). Is it possible that `aspen-jinja2` is accidentally installing an old version of Aspen that requires Cheroot?

**Comment by whit537** [comment]
Or is there some caching going on at Heroku? Did you used to have an older version of Aspen installed and then you upgraded?

**Comment by amitkot** [comment]
Yes, I used to have this site run on an older version of aspen.
Is this caching a feature if Heroku that I can turn off? Have you
encountered it before?

**Comment by whit537** [comment]
Maybe ask on the Heroku Python forum?

https://discussion.heroku.com/category/python

**Comment by whit537** [comment]
I also found this hint googling for "heroku python cache"

> If you specify a different Python runtime than a previous build, your application’s build cache will be purged.

https://devcenter.heroku.com/articles/python-support#changing-runtimes

Check out the Python buildpack docs/source here:

https://github.com/heroku/heroku-buildpack-python

**Comment by whit537** [comment]
Did you ever figure this one out, @amitkot?

**Comment by amitkot** [comment]
Sorry for the late reply.
This was indeed an issue with Heroku Caching.
I installed the [heroku-repo](https://github.com/heroku/heroku-repo) plugin and used it to purge the cache and rebuild my app.

It worked and my website stopped crashing.
Thanks for the lead! :+1:

**Comment by whit537** [comment]
Yay! Thanks for following up, @amitkot, and for using Aspen! :-)
