### ISSUE TITLE
"Core Algorithms" page is 500

### ISSUE THREAD

**Issue by whit537** [gratipay/aspen-python#453]
http://aspen.io/core-algorithms/

I forget ... are you able to look at this, @pjz?

**Comment by whit537** [comment]
```
2015-06-21T04:27:28.829417+00:00 app[web.1]: Traceback (most recent call last):
2015-06-21T04:27:28.829430+00:00 app[web.1]:   File "./aspen/website.py", line 40, in __call__
2015-06-21T04:27:28.829453+00:00 app[web.1]:     return self.wsgi_app(environ, start_response)
2015-06-21T04:27:28.829489+00:00 app[web.1]:   File "./aspen/website.py", line 53, in wsgi_app
2015-06-21T04:27:28.829519+00:00 app[web.1]:     wsgi = self.respond(environ)['response']
2015-06-21T04:27:28.829541+00:00 app[web.1]:   File "./aspen/website.py", line 63, in respond
2015-06-21T04:27:28.829577+00:00 app[web.1]:     , _return_after=return_after
2015-06-21T04:27:28.829599+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/algorithm.py", line 288, in run
2015-06-21T04:27:28.829680+00:00 app[web.1]:     new_state = function(**deps.as_kwargs)
2015-06-21T04:27:28.829702+00:00 app[web.1]:   File "./aspen/algorithms/website.py", line 172, in log_result_of_request
2015-06-21T04:27:28.829755+00:00 app[web.1]:     if website.logging_threshold > 0: # short-circuit
2015-06-21T04:27:28.829786+00:00 app[web.1]: AttributeError: 'module' object has no attribute 'logging_threshold'
```

**Comment by whit537** [comment]
First attempt locally worked fine.

**Comment by whit537** [comment]
Interesting that it's a `'module'` object. I would expect it to be a `Website` instance.

**Comment by whit537** [comment]
Fixed somewhere under https://github.com/gratipay/aspen-python/issues/459.

**Comment by whit537** [comment]
http://aspen.io/core-algorithms/
